name: ci

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # Restores renv.lock + caches packages automatically
      - uses: r-lib/actions/setup-renv@v2

      - name: Run pipeline
        shell: bash
        run: |
          set -euxo pipefail
          make download
          make metadata
          make de
          make report
